name: Build and upload to PyPI.

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      CIBW_SKIP: "cp27-* cp34-* pp27-*"
      CIBW_BEFORE_BUILD: "pip install cython"
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        name: Set up QEMU

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.0.0a2 cython

      - name: Build wheels
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_ARCHS_LINUX: auto aarch64
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      CIBW_SKIP: "cp27-* cp34-* pp27-*"
      CIBW_BEFORE_BUILD: "pip install cython"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Build sdist
        run: |
          pip install -U cython
          python setup.py build_ext --inplace --cython
          python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
